"""Most of the figures for the research paper, matching
map1_vulnerability_score.py's style; pulls from data/ CSVs where
available. Needs matplotlib, pandas, numpy, scipy.

Note on numbering: the function/file names below (fig2, fig3, fig4...)
are just this script's own internal order, not the paper's Figure
numbers. They line up for some (fig4, fig6, fig7 match the paper's
Figure 4, 6, 7) but not for others (this script's fig2 makes the
paper's Figure 1, fig3 makes Figure 2, fig5 makes Figure 3). Each
function's comment below now says which paper Figure it actually
produces, so this doesn't have to be worked out again by hand.

Also: the paper's Figure 5 (compound_vulnerability_score.png) is NOT
generated by this script at all -- that one comes from
compound_vulnerability_score.py directly.
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

OUT_DIR = "outputs/plots"
os.makedirs(OUT_DIR, exist_ok=True)

BLUE = "#2c7fb8"
RED = "#e34a33"
GREEN = "#31a354"
PURPLE = "#756bb1"
ORANGE = "#fd8d3c"
EDGE = "#333333"

ISLAND_ORDER = ["Seychelles", "Maldives", "Lakshadweep", "Fiji", "Canary Islands"]
ISLAND_COLOR = {
    "Maldives": BLUE, "Seychelles": RED, "Fiji": GREEN,
    "Canary Islands": PURPLE, "Lakshadweep": ORANGE,
}
ISLAND_FILE_MAP = {
    "Maldives": "maldives", "Seychelles": "seychelles", "Fiji": "fiji",
    "Canary Islands": "canary", "Lakshadweep": "lakshadweep",
}


def source_caption(ax_fig, text):
    plt.figtext(0.5, 0.01, text, ha="center", fontsize=8, color="gray")


# ------------------------------------------------------------------
# Makes the paper's Figure 1 — Physical Exposure by Island (settlement-based)
# ------------------------------------------------------------------
def fig2_physical_exposure():
    df = pd.read_csv("data/slr_exposure_summary.csv")
    df["island"] = df["island"].str.title().replace({"Canary": "Canary Islands"})
    df = df.sort_values("pct_at_risk", ascending=True)

    fig, ax = plt.subplots(figsize=(11, 7))
    colors = [RED if p >= 50 else BLUE for p in df["pct_at_risk"]]
    bars = ax.barh(df["island"], df["pct_at_risk"], color=colors, edgecolor=EDGE, linewidth=0.8)

    for bar, pct, total in zip(bars, df["pct_at_risk"], df["total"]):
        ax.text(bar.get_width() + 1.2, bar.get_y() + bar.get_height() / 2,
                 f"{pct:.1f}% (n={int(total)})", va="center", fontsize=10, fontweight="bold")

    ax.set_xlabel("% of Settlements At or Below 1m Elevation Threshold", fontsize=11)
    ax.set_title(
        "Physical Exposure by Island\n"
        "Share of settlement locations at or below the 1-meter sea-level-rise threshold",
        fontsize=13, fontweight="bold", pad=15
    )
    ax.set_xlim(0, 112)
    ax.grid(axis="x", alpha=0.3)

    source_caption(fig, "DOUBLE JEOPARDY — Source: Copernicus DEM GLO-30, OpenStreetMap settlements")
    plt.tight_layout()
    out = os.path.join(OUT_DIR, "fig2_physical_exposure_by_island.png")
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")


# ------------------------------------------------------------------
# Makes the paper's Figure 2 — Settlement-based vs Population-weighted Exposure
# ------------------------------------------------------------------
def fig3_settlement_vs_population():
    settlement_df = pd.read_csv("data/slr_exposure_summary.csv")
    settlement_df["island"] = settlement_df["island"].str.title().replace({"Canary": "Canary Islands"})
    settlement_pct = dict(zip(settlement_df["island"], settlement_df["pct_at_risk"]))

    # Population-weighted exposure %, from population_weighted_exposure.py's
    # boundary-polygon-masked run (APPLY_BOUNDARY_MASK = True, boundaries
    # rebuilt from OpenStreetMap coastline data via shapely.ops.polygonize()
    # / OSM's land-polygons dataset for Fiji, and validated against
    # independently sourced land area figures -- see the paper's Section 6
    # for the full boundary rebuild and validation, and the numerator/
    # denominator verification behind the Maldives/Seychelles order flip).
    # Maldives and Lakshadweep also use the corrected _elevation_v2.tif and
    # the raster-level void-exclusion check -- see the paper's Section 6 for
    # the full DEM coverage-gap fix.
    population_pct = {
        "Maldives": 14.9, "Seychelles": 14.2, "Lakshadweep": 2.1,
        "Fiji": 1.6, "Canary Islands": 1.4,
    }

    islands = ISLAND_ORDER
    x = np.arange(len(islands))
    width = 0.35

    fig, ax = plt.subplots(figsize=(11, 7))
    bars1 = ax.bar(x - width / 2, [settlement_pct[i] for i in islands], width,
                    label="Settlement-based", color=BLUE, edgecolor=EDGE, linewidth=0.8)
    bars2 = ax.bar(x + width / 2, [population_pct[i] for i in islands], width,
                    label="Population-weighted", color=RED, edgecolor=EDGE, linewidth=0.8)

    for bars in (bars1, bars2):
        for bar in bars:
            h = bar.get_height()
            ax.text(bar.get_x() + bar.get_width() / 2, h + 1.5, f"{h:.1f}%",
                     ha="center", fontsize=9, fontweight="bold")

    ax.set_xticks(x)
    ax.set_xticklabels(islands, fontsize=10)
    ax.set_ylabel("% Exposed to 1m SLR Threshold", fontsize=11)
    ax.set_ylim(0, 112)
    ax.set_title(
        "Settlement-Based vs. Population-Weighted Physical Exposure\n"
        "Measures mostly agree on ranking, but Maldives narrowly leads Seychelles on population weighting",
        fontsize=13, fontweight="bold", pad=15
    )
    ax.legend(loc="upper right", fontsize=10, frameon=True)
    ax.grid(axis="y", alpha=0.3)

    source_caption(fig, "DOUBLE JEOPARDY — Source: Copernicus DEM GLO-30, OpenStreetMap, WorldPop 2020 "
                         "(Fiji reflects ~97.6% of national population; Lau Islands excluded, no elevation coverage)")
    plt.tight_layout()
    out = os.path.join(OUT_DIR, "fig3_settlement_vs_population_weighted.png")
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")


# ------------------------------------------------------------------
# Makes the paper's Figure 4 — Coral Thermal Stress Time Series with trend lines
# ------------------------------------------------------------------
def fig4_coral_trends():
    # Precomputed OLS trend (intercept + slope/year, years since series start)
    # and Mann-Kendall significance, from the robustness-check trend test.
    # p-values are from the SEASONAL Mann-Kendall test (period=12), not the
    # plain/original test -- DHW is structurally seasonal, so the plain
    # test's independence assumption doesn't hold here. See coral_trend_test.py.
    trend_info = {
        "Maldives": {"intercept": 0.0895, "slope_per_year": 0.00450, "significant": True, "p": 0.0046},
        "Seychelles": {"intercept": -0.0668, "slope_per_year": 0.02532, "significant": True, "p": 0.0069},
        "Fiji": {"intercept": 0.3250, "slope_per_year": 0.00151, "significant": False, "p": 0.2437},
        "Lakshadweep": {"intercept": 0.1072, "slope_per_year": 0.00254, "significant": False, "p": 0.3725},
        "Canary Islands": {"intercept": 0.4762, "slope_per_year": 0.01905, "significant": False, "p": 0.6196},
    }

    fig, ax = plt.subplots(figsize=(13, 7.5))

    for island in ISLAND_ORDER:
        file_key = ISLAND_FILE_MAP[island]
        path = f"data/coral_bleaching/{file_key}_dhw_timeseries.csv"
        df = pd.read_csv(path, skiprows=[1])
        df["time"] = pd.to_datetime(df["time"])
        df = df.sort_values("time")
        color = ISLAND_COLOR[island]

        ax.plot(df["time"], df["degree_heating_week"], color=color, linewidth=1.3,
                alpha=0.85, label=None)

        info = trend_info[island]
        start_date, end_date = df["time"].iloc[0], df["time"].iloc[-1]
        years_elapsed = (end_date - start_date).days / 365.25
        y_start = info["intercept"]
        y_end = info["intercept"] + info["slope_per_year"] * years_elapsed
        sig_label = "significant" if info["significant"] else "not significant"
        ax.plot([start_date, end_date], [y_start, y_end], color=color, linewidth=2.4,
                 linestyle="--",
                 label=f"{island} trend (MK {sig_label}, p={info['p']:.3f})")

    ax.axhline(4, color="orange", linestyle=":", linewidth=1.2)
    ax.axhline(8, color="darkred", linestyle=":", linewidth=1.2)
    ax.text(ax.get_xlim()[0], 4.15, " Bleaching threshold (4°C-wk)", fontsize=8, color="darkorange", va="bottom")
    ax.text(ax.get_xlim()[0], 8.15, " Severe bleaching/mortality (8°C-wk)", fontsize=8, color="darkred", va="bottom")

    ax.set_xlabel("Date", fontsize=11)
    ax.set_ylabel("Degree Heating Week (°C-weeks)", fontsize=11)
    ax.set_title(
        "Coral Thermal Stress Over Time (1996–2020), with Trend Lines\n"
        "Dashed lines are OLS fits; significance assessed via Mann-Kendall trend test on the full series",
        fontsize=13, fontweight="bold", pad=15
    )
    ax.grid(alpha=0.3)
    ax.legend(loc="upper left", fontsize=8.5, frameon=True, ncol=1)

    source_caption(fig, "DOUBLE JEOPARDY — Source: NOAA Coral Reef Watch")
    plt.tight_layout()
    out = os.path.join(OUT_DIR, "fig4_coral_thermal_stress_trends.png")
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")


# ------------------------------------------------------------------
# Makes the paper's Figure 3 (NOT Figure 5 — see the module note up top)
# — Mangrove Extent Over Three Time Points
# ------------------------------------------------------------------
def fig5_mangrove_extent():
    # From mangrove_3point_comparison.py's validated output (area in an
    # equal-area projection, EPSG:6933). Only islands with mangroves present.
    mangrove_data = {
        "Maldives": [0.97, 0.97, 0.97],
        "Seychelles": [3.83, 3.84, 3.83],
        "Fiji": [485.72, 487.97, 488.41],
    }
    years = [1996, 2010, 2020]

    fig, ax = plt.subplots(figsize=(10, 6.5))
    for island, values in mangrove_data.items():
        ax.plot(years, values, marker="o", markersize=9, linewidth=2.6,
                color=ISLAND_COLOR[island], label=island)
        for yr, v in zip(years, values):
            ax.text(yr, v, f"  {v:.2f}", fontsize=8.5, va="bottom", color=ISLAND_COLOR[island])

    ax.set_xticks(years)
    ax.set_xlabel("Year", fontsize=11)
    ax.set_ylabel("Mangrove Area (km²)", fontsize=11)
    ax.set_yscale("log")
    ax.set_title(
        "Mangrove Extent Over Time (1996, 2010, 2020)\n"
        "Log scale — extent is essentially flat for every island, no net decline detected",
        fontsize=13, fontweight="bold", pad=15
    )
    ax.grid(alpha=0.3, which="both")
    ax.legend(loc="center left", fontsize=10, frameon=True)

    source_caption(fig, "DOUBLE JEOPARDY — Source: Global Mangrove Watch (GMW), area computed in EPSG:6933")
    plt.tight_layout()
    out = os.path.join(OUT_DIR, "fig5_mangrove_extent_over_time.png")
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")


# ------------------------------------------------------------------
# Makes the paper's Figure 6 — Governance Alignment (Vulnerability vs WDPA coverage)
# ------------------------------------------------------------------
def fig6_governance_alignment():
    df = pd.read_csv("data/governance_alignment_test.csv")

    # Lakshadweep's WDPA figure is a missing-data placeholder (0.0, not a
    # measured value -- see wdpa_coastal_buffer.py), so it's excluded from
    # the correlation itself even though it's still plotted below for
    # context. See governance_correlation_test.py. It's given a visually
    # distinct (hollow, greyed-out) marker below specifically so a reader
    # can't mistake it for one of the n=4 points the r/p is computed from.
    is_excluded = df.get("excluded_from_correlation", pd.Series([False] * len(df))).astype(bool)
    corr_df = df[~is_excluded]

    r, p = stats.pearsonr(corr_df["vulnerability_score"], corr_df["wdpa_ratio"])
    n = len(corr_df)
    z = np.arctanh(r)
    se = 1 / np.sqrt(n - 3)
    ci_low, ci_high = np.tanh(z - 1.96 * se), np.tanh(z + 1.96 * se)

    fig, ax = plt.subplots(figsize=(10, 7))

    included = df[~is_excluded]
    excluded = df[is_excluded]

    included_colors = [ISLAND_COLOR[i.title().replace("Canary", "Canary Islands")] for i in included["island"]]
    ax.scatter(included["vulnerability_score"], included["wdpa_ratio"], s=140, c=included_colors,
               edgecolor=EDGE, linewidth=1, zorder=3, label=f"Included in correlation (n={n})")

    if len(excluded):
        ax.scatter(excluded["vulnerability_score"], excluded["wdpa_ratio"], s=140,
                   facecolor="none", edgecolor="#888888", linewidth=2, linestyle="--",
                   hatch="//", zorder=3, label="Excluded — no WDPA data (context only)")

    for _, row in df.iterrows():
        label = row["island"].title().replace("Canary", "Canary Islands")
        excl = is_excluded[row.name]
        if excl:
            label += "\n(excluded — no WDPA data)"
        ax.annotate(label, (row["vulnerability_score"], row["wdpa_ratio"]),
                    textcoords="offset points", xytext=(10, -22) if excl else (8, 6),
                    fontsize=10, fontweight="bold" if not excl else "normal",
                    color=EDGE if not excl else "#888888")

    # OLS best-fit line for visual reference — fit on the same n=4 used for
    # the reported correlation, so the line matches the r/p in the title
    slope, intercept, *_ = stats.linregress(corr_df["vulnerability_score"], corr_df["wdpa_ratio"])
    xs = np.linspace(corr_df["vulnerability_score"].min(), corr_df["vulnerability_score"].max(), 50)
    ax.plot(xs, intercept + slope * xs, color=EDGE, linestyle="--", linewidth=1.3, alpha=0.7, zorder=2,
            label=f"OLS fit (n={n} points only)")

    ax.set_xlabel("Compound Vulnerability Score", fontsize=11)
    ax.set_ylabel("WDPA Coastal Protected-Area Ratio", fontsize=11)
    ax.set_title(
        "Governance Alignment: Risk vs. Protected-Area Coverage\n"
        f"r = {r:.3f}, p = {p:.3f}, 95% CI [{ci_low:.2f}, {ci_high:.2f}] (n={n} — hollow point excluded)",
        fontsize=13, fontweight="bold", pad=15
    )
    ax.legend(loc="upper left", fontsize=9, framealpha=0.9)
    ax.grid(alpha=0.3)

    source_caption(fig, "DOUBLE JEOPARDY — Source: World Database on Protected Areas (WDPA), "
                         "10km coastal buffer; compound vulnerability score (this study)")
    plt.tight_layout()
    out = os.path.join(OUT_DIR, "fig6_governance_alignment.png")
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")
    print(f"  Governance correlation: r={r:.3f}, p={p:.3f}, 95% CI=[{ci_low:.2f}, {ci_high:.2f}] (n={n})")


# ------------------------------------------------------------------
# Makes the paper's Figure 7 — Compound Vulnerability Score: Weighting Sensitivity Curve
# ------------------------------------------------------------------
def fig7_weighting_sensitivity():
    # Same normalize() logic as compound_vulnerability_score.py. slr_data is
    # read from the same CSV Figures 1/2 use rather than hardcoded here, so
    # a corrected exposure figure (e.g. the Fiji NoData fix) can't silently
    # drift out of sync between this figure and the others.
    _slr_df = pd.read_csv("data/slr_exposure_summary.csv").set_index("island")
    slr_data = {label: _slr_df.loc[key, "pct_at_risk"] for label, key in ISLAND_FILE_MAP.items()}
    coral_decline = {"Maldives": 0.17, "Seychelles": 0.68, "Fiji": 0.10, "Canary Islands": -0.05, "Lakshadweep": 0.08}

    def normalize(d):
        values = list(d.values())
        min_v, max_v = min(values), max(values)
        return {k: (v - min_v) / (max_v - min_v) if max_v > min_v else 0 for k, v in d.items()}

    slr_norm = normalize(slr_data)
    coral_norm = normalize(coral_decline)

    weights = np.linspace(0, 1, 101)  # physical-exposure weight, 0% to 100%
    fig, ax = plt.subplots(figsize=(11, 7))

    for island in ISLAND_ORDER:
        scores = [slr_norm[island] * w + coral_norm[island] * (1 - w) for w in weights]
        ax.plot(weights * 100, scores, color=ISLAND_COLOR[island], linewidth=2.4, label=island)

    ax.axvline(50, color=EDGE, linestyle=":", linewidth=1.3)
    ax.text(51, 0.97, "Weighting used in this study (50/50)", fontsize=8.5, color=EDGE)

    ax.set_xlabel("Physical Exposure Weight (%)  —  remainder assigned to coral ecosystem decline", fontsize=10.5)
    ax.set_ylabel("Compound Vulnerability Score (normalized, 0–1)", fontsize=11)
    ax.set_title(
        "Compound Vulnerability Score — Weighting Sensitivity\n"
        "Seychelles leads across the entire 0-100% weighting range",
        fontsize=13, fontweight="bold", pad=15
    )
    ax.set_xlim(0, 100)
    ax.set_ylim(-0.05, 1.05)
    ax.grid(alpha=0.3)
    ax.legend(loc="center left", fontsize=10, frameon=True)

    source_caption(fig, "DOUBLE JEOPARDY — Derived from slr_exposure_summary.csv and coral DHW trend data (this study)")
    plt.tight_layout()
    out = os.path.join(OUT_DIR, "fig7_weighting_sensitivity_curve.png")
    plt.savefig(out, dpi=200)
    plt.close(fig)
    print(f"Saved: {out}")


if __name__ == "__main__":
    print("Generating additional DOUBLE JEOPARDY figures...\n")
    fig2_physical_exposure()
    fig3_settlement_vs_population()
    fig4_coral_trends()
    fig5_mangrove_extent()
    fig6_governance_alignment()
    fig7_weighting_sensitivity()
    print(f"\nDone. All figures saved in: {OUT_DIR}/")
